# Generated by Django 5.1.3 on 2024-11-29 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEYV', '0009_alter_producto_id_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Email',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ID_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEYV.usuario'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Tipo_prod',
            field=models.IntegerField(choices=[(1, 'Linterna'), (2, 'Herramienta')]),
        ),
    ]
