# Generated by Django 5.1.3 on 2024-11-29 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appEYV', '0011_remove_cliente_id_usuario_cliente_usuario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
