# Generated by Django 5.1.3 on 2024-11-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEYV', '0012_delete_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_pago', models.CharField(max_length=20, unique=True)),
                ('Tipo_pago', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=20)),
                ('email_comprador', models.EmailField(max_length=254)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(max_length=10)),
                ('fecha', models.DateTimeField()),
                ('datos_raw', models.JSONField()),
            ],
        ),
    ]
